### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by orschiro** [cpiehl/py2fa#1]
Thank you @cpiehl. :-)

I really like your simply GUI.

However, after a while the GUI simply stops working.

![image](https://cloud.githubusercontent.com/assets/170947/20789049/59e743dc-b7b3-11e6-9912-44b80212b26e.png)

**Comment by cpiehl** [comment]
Seems it was a threading issue.  I left it running for a while on two different computers running Windows and Linux and no freezes, so I'm assuming it's fixed.

**Comment by orschiro** [comment]
Thank you. It seems to be working now. :-)
