### ISSUE TITLE
How do I add an application?

### ISSUE THREAD

**Issue by orschiro** [cpiehl/py2fa#2]
Dear @cpiehl, 

I tried to add Dropbox as follows. 

![image](https://cloud.githubusercontent.com/assets/170947/20808193/02cfcc14-b802-11e6-8a06-41169711d214.png)

**Comment by cpiehl** [comment]
Oops, that's two bugs on my part.  Fixed the padding for base32 decoding and it looks like it accepts your key now.  Make sure you get a new key from Dropbox now if you posted your real one.

**Comment by orschiro** [comment]
Thank you. It wasn't my real one. :-)

How do I delete an application?

![image](https://cloud.githubusercontent.com/assets/170947/20810025/37f984f6-b808-11e6-8790-4ca1ccacd300.png)

**Comment by cpiehl** [comment]
Not implemented yet, but it's next on my list.  Until then you can do it manually by opening the py2fa.json file and removing the entry.

`{"accounts": {"Dropbox": "hc3weknlzxq3hxoc23ypbouiex"}, "resHeight": 300, "resWidth": 200}`
Remove `"Dropbox": "hc3weknlzxq3hxoc23ypbouiex"`

**Comment by orschiro** [comment]
Cool, thank you. :-)
