### ISSUE TITLE
None output

### ISSUE THREAD

**Issue by orschiro** [cpiehl/py2fa#4]
Hello @cpiehl,

Please take a look at this "None" output.

![image](https://cloud.githubusercontent.com/assets/170947/20884128/d01682d2-bae9-11e6-8c3e-8cf6ccc37f7c.png)

**Comment by cpiehl** [comment]
It was some debug output that accidentally got left in.  Fixed,

**Comment by orschiro** [comment]
Thank you for the fix. :-)

5. Dec 2016 17:20 by notifications@github.com:
