### ISSUE TITLE
My first try to use this

### ISSUE THREAD

**Issue by meckli** [cpiehl/py2fa#5]
```
~/Downloads/py2fa $ python main.py
  File "main.py", line 5
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```
Don't know why. What have I done wrong?

**Comment by cpiehl** [comment]
It looks like you've saved the HTML page rather than the raw source code.  Try this https://raw.githubusercontent.com/cpiehl/py2fa/master/main.py

**Comment by meckli** [comment]
Well, you're right. I'd better gone to sleep :-).
