### ISSUE TITLE
Missing documentation for adding valid secret

### ISSUE THREAD

**Issue by urbalazs** [cpiehl/py2fa#6]
Hi @cpiehl 
I tried to add an account, but I got "Invalid Secret" error message for these secrets:

- h4hge9fwfcn8e4cg
- Secret1234
- a1s2d3f4g5h6j7k8

These are valid secrets:
- This is a secret (I typed it with spaces, but it is stored without spaces)
- 4fwhhq43ttumxguc (I generated many random strings, and only this one is accepted)

Please add some information to README file, how to generate valid secret.

**Comment by cpiehl** [comment]
You're right, I really dropped the ball on documentation here.  "Invalid Secret" is just too vague of an error message, but trying those same keys in Google Authenticator shows why they aren't accepted:

- h4hge9fwfcn8e4cg: "Key value has illegal character" when I get to 9
- Secret1234: "Key value is too short"
- a1s2d3f4g5h6j7k8: "Key value has illegal character" at 8

I'll update with better error messages and add the rules to README soon.

**Comment by urbalazs** [comment]
I close this issue, because it was fixed with https://github.com/cpiehl/py2fa/commit/0044dd4b9e7192d4a02242ca57df73bccce9edf0 and https://github.com/cpiehl/py2fa/commit/81867fd2317a3d170f25eb99f58cc1fb86e4ae17
